# App-of-Apps - All platform components
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform components
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-components
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: argocd
            namespace: argocd
            path: platform/argocd
          - name: sealed-secrets
            namespace: kube-system
            path: platform/sealed-secrets
          - name: crossplane
            namespace: crossplane-system
            path: platform/crossplane
          - name: monitoring
            namespace: monitoring
            path: platform/monitoring
          - name: backstage-infra
            namespace: backstage
            path: platform/backstage
          - name: gateway-api
            namespace: nginx-gateway
            path: platform/gateway-api
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: platform
      source:
        repoURL: https://github.com/malconip/platform-lab.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
# Backstage Helm Chart (standalone - uses external PostgreSQL)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: 1.9.0
    helm:
      values: |
        backstage:
          image:
            registry: ghcr.io
            repository: backstage/backstage
            tag: latest
          
          extraEnvVars:
            - name: APP_CONFIG_backend_baseUrl
              value: http://backstage.localhost
            - name: APP_CONFIG_app_baseUrl
              value: http://backstage.localhost
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: backstage
            - name: POSTGRES_PASSWORD
              value: backstage
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        
        # Disable built-in ingress - using Gateway API
        ingress:
          enabled: false
        
        # Disable built-in PostgreSQL - using custom deployment
        postgresql:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
