apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: 1.9.0
    helm:
      values: |
        backstage:
          image:
            registry: ghcr.io
            repository: backstage/backstage
            tag: latest
          
          extraEnvVars:
            - name: APP_CONFIG_backend_baseUrl
              value: http://localhost:7007
            - name: APP_CONFIG_app_baseUrl
              value: http://localhost:7007
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        
        postgresql:
          enabled: true
          auth:
            password: backstage
          primary:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
